"""empty message

<<<<<<< HEAD:migrations/versions/d9e613a3354a_.py
<<<<<<<< HEAD:migrations/versions/f0288a8a4e6a_.py
Revision ID: f0288a8a4e6a
Revises: 
Create Date: 2024-12-12 00:40:49.984155
========
Revision ID: d9e613a3354a
Revises: 
Create Date: 2024-12-11 23:52:10.066791
>>>>>>>> e32b22d7cb3a96fd5421000284864ee6eb5cc86d:migrations/versions/d9e613a3354a_.py
=======
Revision ID: 56285079d551
Revises: 
Create Date: 2024-12-13 22:15:20.110516
>>>>>>> f8bb2a23ea5130ec306494b9c7bf50a8a693c66e:migrations/versions/56285079d551_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/d9e613a3354a_.py
<<<<<<<< HEAD:migrations/versions/f0288a8a4e6a_.py
revision = 'f0288a8a4e6a'
========
revision = 'd9e613a3354a'
>>>>>>>> e32b22d7cb3a96fd5421000284864ee6eb5cc86d:migrations/versions/d9e613a3354a_.py
=======
revision = '56285079d551'
>>>>>>> f8bb2a23ea5130ec306494b9c7bf50a8a693c66e:migrations/versions/56285079d551_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('num_funcionario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_funcionario')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lunes', sa.String(length=20), nullable=True),
    sa.Column('martes', sa.String(length=20), nullable=True),
    sa.Column('miercoles', sa.String(length=20), nullable=True),
    sa.Column('jueves', sa.String(length=20), nullable=True),
    sa.Column('viernes', sa.String(length=20), nullable=True),
    sa.Column('sabado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('user')
    op.drop_table('menu_options')
    op.drop_table('menu')
    # ### end Alembic commands ###
