"""empty message

<<<<<<<< HEAD:migrations/versions/c8b78dd2a302_.py
Revision ID: c8b78dd2a302
Revises: 
Create Date: 2024-12-11 23:11:07.484267
========
Revision ID: 689562fcad08
Revises: 
Create Date: 2024-12-11 22:48:05.209007
>>>>>>>> fea9b29321b5fee3106bc933a414bda8760c8845:migrations/versions/689562fcad08_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/c8b78dd2a302_.py
revision = 'c8b78dd2a302'
========
revision = '689562fcad08'
>>>>>>>> fea9b29321b5fee3106bc933a414bda8760c8845:migrations/versions/689562fcad08_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('num_funcionario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('num_funcionario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('reserva')
    op.drop_table('menu_options')
    op.drop_table('menu')
    # ### end Alembic commands ###
