"""empty message

Revision ID: 7ad7388309c1
Revises: 07a645bb2b7e
Create Date: 2024-12-11 14:08:07.231684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad7388309c1'
down_revision = '07a645bb2b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunes', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('martes', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('miercoles', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('jueves', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('viernes', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sabado', sa.String(length=20), nullable=False))
        batch_op.drop_column('hora')
        batch_op.drop_column('dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('sabado')
        batch_op.drop_column('viernes')
        batch_op.drop_column('jueves')
        batch_op.drop_column('miercoles')
        batch_op.drop_column('martes')
        batch_op.drop_column('lunes')

    # ### end Alembic commands ###
