"""empty message

Revision ID: daf42b2c231f
Revises: 7ad7388309c1
Create Date: 2024-12-11 14:11:05.145872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf42b2c231f'
down_revision = '7ad7388309c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lunes',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('martes',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('miercoles',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('jueves',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('viernes',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('sabado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('sabado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('viernes',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('jueves',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('miercoles',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('martes',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('lunes',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
