"""empty message

Revision ID: db27311263e2
Revises: 07a645bb2b7e
Create Date: 2024-12-10 14:41:04.817838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db27311263e2'
down_revision = '07a645bb2b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_options')
    # ### end Alembic commands ###
